# This is my first workflow
name: workflow1
on: 
  workflow_dispatch:
  push:
env:
 greetings: hello
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      last_name: singh
      greetings: welcome
    steps:
       - name: this is first step
         run: |
           echo $greetings! $name $last_name is the owner of $GITHUB_REPOSITORY repo for application ${{ vars.APP_NAME }} . Reachout to $name for any updates.
           echo This step is running on $RUNNER_OS on instance $RUNNER_NAME
           echo ${{ vars.APP_NAME }} is running on ${{ vars.SERVER_NAME }}
           echo Application password is ${{ secrets.DB_PASSWD }}
           sleep 10
         env:
            name: Gagandeep
            greetings: "GoodMorning"
       - name: second step
         run: |
           uname -a
           echo $greetings! $name $last_name is the owner of this repo. Reachout to $name for any updates.
           touch /tmp/gagandeep
           sleep 10
       - run: echo "step 3"
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
       - name: this is first step
         run: |
           echo $greetings! $name $last_name is the owner of this repo. Reachout to $name for any updates.
           echo This step is running on $RUNNER_OS on instance $RUNNER_NAME
           echo ${{ vars.APP_NAME }} is running on ${{ vars.SERVER_NAME }}
           sleep 10
       - name: second step
         run: |
           uname -a
           cat /etc/os-release
           touch /tmp/gagandeep
           sleep 10
       - run: echo "step 3"
       

