name: pipeline1
on: 
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: step zero
         uses: actions/checkout@v4.1.2
       - name: this is first build step
         run: ls -l
       - name: this is Second build step
         run: |
           sleep 10
           exit 1
           echo hello from step 2
       - name: this is third step 
         id: step3 
         run: echo hello from step 2 
         if : ${{ failure() && steps.step3.conclusion == 'failure' }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
       - name: this is first test step
         run: echo hello from step 1
       - name: this is Second test step
         run: |
           sleep 10
           echo hello from step 2
       - name: debug step 
         run: echo "Job got failed" 
  stage:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: test
    steps:
       - name: this is first stage step
         run: echo hello from step 1
       - name: this is Second stage step
         run: |
           sleep 10
           echo hello from step 2
  deploy:
    runs-on: ubuntu-latest
    needs: stage
    steps:
       - name: this is first prod step
         run: echo hello from step 1
       - name: this is Second prod step
         run: |
           sleep 10
           echo hello from step 2         
